import scipy.sparse as sparse
import numpy as np
import random

In [64]:
import scipy.sparse as sparse
import numpy as np
import random

In [139]:
# generate sparse matrix w/ given shape and density 
def generate_sparse_binary(m_,n_,lambda_):
    XX=sparse.rand(m_,n_,density=lambda_, format='csc')
    XX[np.nonzero(XX)]=1 
    return XX

In [46]:
sumz[:,45]

matrix([[0.]])

In [32]:
np.sum([XX.sum(axis=0)==3])

1

In [30]:
# descending sort, indices
np.argsort(-XX.sum(axis=0))

matrix([[ 1, 73, 24, 79, 87, 26, 10,  8, 27,  4, 67,  7, 28, 56, 59, 31,
         32, 78, 69, 39, 40, 42, 68, 46, 47, 50, 75, 99, 81, 23, 84, 21,
         83, 13, 93, 89, 15, 82, 94, 95, 96, 66, 64, 97, 63, 62, 65, 70,
         72, 91, 71, 90, 74, 88, 76, 77, 86, 85, 80, 92, 61,  0, 58, 25,
         22, 20, 19, 18, 17, 16, 14, 12, 11,  9,  6,  5,  3,  2, 29, 30,
         33, 34, 57, 55, 54, 53, 52, 51, 98, 60, 48, 44, 43, 41, 38, 37,
         36, 35, 45, 49]])

In [ ]:
def shuffle_in_bins(sorted_idx, bins_):
    new_idx=[]

In [56]:
split=round(100/7)
for i in range(7):
    print()

14

In [111]:
def make_bins(idx_, bins_):
    d_=round(len(idx_)/bins_)
    splits=[idx_[i*d_:(i+1)*d_] for i in range(bins_-1)]
    splits.append(idx_[(bins_-1)*d_:])
    return splits


In [63]:
tst=list(range(100))
make_bins(tst)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
 [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
 [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
 [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
 [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

In [130]:
def shuffle_bins(xx):
    shuff_xx=[]
    for x in xx:
        sub_shuff=random.sample(x, len(x))
        shuff_xx.extend(sub_shuff)
    return shuff_xx

In [ ]:
tst=list(range(100))
splits=make_bins(tst)
shuffle_bins(splits), splits

In [83]:
XX=generate_sparse_binary(m_=10,n_=1000, lambda_=0.3)


In [112]:
XX=generate_sparse_binary(m_=10,n_=1000, lambda_=0.1)
np.argsort(-XX.sum(axis=0))

matrix([[184, 904, 243, 728, 211, 592, 510, 671,  85, 100, 139, 340, 905,
         473, 577,  61, 218, 872, 931, 223,  91,  90, 963, 894,  84, 229,
         233, 688, 502, 240, 686, 969, 151, 803, 629, 164, 632, 946, 146,
         468, 783, 177, 375, 795, 781, 607, 780, 647, 888, 378, 119, 118,
         492, 206, 108, 217, 401, 679, 317, 547, 914,  32, 308, 421,  12,
         859, 822, 704, 254, 809,   5,  49, 448, 854, 871, 353, 309, 909,
         538, 352, 285, 623, 910, 519, 526, 541, 518, 890, 491, 901, 190,
         350, 609, 947, 305, 166, 363, 306, 945, 790, 165, 175, 838, 907,
         529, 886, 935, 181, 816, 185, 304, 189, 202, 247, 204, 998, 801,
         561, 230, 787, 231, 580, 807, 564, 235, 237, 331, 325, 251, 504,
         829, 328, 569, 327, 808, 203, 892, 336, 597, 825, 804, 343, 593,
         550, 213, 428, 496, 272, 270, 320, 811, 338, 337, 266, 554, 264,
         557, 225, 160, 743, 476, 981, 708,  45, 446, 870, 978, 693, 761,
          60,  64,  66, 687, 709, 685,

In [90]:
XX.sum(axis=0)[:,596]

matrix([[6.]])

In [93]:
XX.sum(axis=1)

matrix([[ 92.],
        [ 95.],
        [109.],
        [ 96.],
        [109.],
        [106.],
        [100.],
        [112.],
        [ 95.],
        [ 86.]])

In [91]:
XX.sum(axis=0)[:,499]

matrix([[0.]])

In [114]:
idx_sorted=np.argsort(-XX.sum(axis=0))

In [123]:
idx_sorted.tolist()[0]

[740,
 26,
 630,
 126,
 118,
 864,
 107,
 801,
 185,
 893,
 908,
 666,
 808,
 793,
 172,
 188,
 197,
 750,
 233,
 142,
 845,
 109,
 108,
 103,
 880,
 894,
 898,
 903,
 906,
 155,
 245,
 691,
 923,
 478,
 483,
 451,
 487,
 489,
 441,
 496,
 416,
 395,
 560,
 388,
 585,
 719,
 599,
 631,
 334,
 632,
 636,
 324,
 642,
 307,
 302,
 293,
 682,
 684,
 687,
 624,
 930,
 469,
 947,
 958,
 953,
 976,
 14,
 968,
 932,
 736,
 569,
 570,
 229,
 230,
 232,
 235,
 730,
 576,
 241,
 580,
 564,
 242,
 726,
 581,
 962,
 724,
 723,
 717,
 586,
 710,
 238,
 222,
 985,
 257,
 532,
 784,
 537,
 777,
 404,
 773,
 543,
 959,
 545,
 981,
 200,
 201,
 547,
 203,
 396,
 764,
 763,
 761,
 759,
 757,
 754,
 394,
 751,
 745,
 554,
 387,
 708,
 262,
 705,
 300,
 354,
 23,
 607,
 609,
 657,
 656,
 653,
 645,
 643,
 344,
 24,
 318,
 320,
 623,
 638,
 327,
 628,
 329,
 330,
 331,
 634,
 979,
 16,
 319,
 667,
 668,
 670,
 182,
 700,
 698,
 267,
 594,
 269,
 270,
 272,
 598,
 274,
 276,
 278,
 690,
 280,
 601,
 282,
 35

In [160]:
#example matrix
m_=50
n_=50000
lambda_=0.1
XX=generate_sparse_binary(m_,n_, lambda_)
idx_sorted=np.argsort(-XX.sum(axis=0)).tolist()[0]
splits=make_bins(idx_sorted, 15)

iter_len=[]
iter_idx=[]
iter_coverage=[]
for i in range(500):
    res=minimal_row_coverage_sets(XX,splits)
    iter_len.append(res[0])
    iter_idx.append(res[1])
    iter_coverage.append(res[2])



whippee, early stop at iter 27
whippee, early stop at iter 33
whippee, early stop at iter 25
whippee, early stop at iter 43
whippee, early stop at iter 29
whippee, early stop at iter 41
whippee, early stop at iter 29
whippee, early stop at iter 43
whippee, early stop at iter 35
whippee, early stop at iter 25
whippee, early stop at iter 25
whippee, early stop at iter 33
whippee, early stop at iter 27
whippee, early stop at iter 31
whippee, early stop at iter 23
whippee, early stop at iter 25
whippee, early stop at iter 19
whippee, early stop at iter 27
whippee, early stop at iter 35
whippee, early stop at iter 41
whippee, early stop at iter 27
whippee, early stop at iter 53
whippee, early stop at iter 45
whippee, early stop at iter 25
whippee, early stop at iter 25
whippee, early stop at iter 27
whippee, early stop at iter 31
whippee, early stop at iter 29
whippee, early stop at iter 31
whippee, early stop at iter 35
whippee, early stop at iter 31
whippee, early stop at iter 33
whippee,

In [161]:
min(iter_len)

9

In [159]:
def minimal_row_coverage_sets(XX, splits):
    idx_shuffle=shuffle_bins(splits)

    z=XX[:,idx_shuffle[0]]
    idx_values=[idx_shuffle[0]]
    coverages=[]
    i=1

    while i<len(idx_shuffle): 
        d0=z.nnz #l0 norm of z=number of nonzeros=row coverage
        
        if d0==m_: #achieved full coverage of rows!
            print('whippee, early stop at iter '+str(i))
            break
        else: # compare next two vectors and see which increases row coverage
            d1=(z+XX[:,idx_shuffle[i]]).nnz #l0 norm of sum vector plus next x1
            d2=(z+XX[:,idx_shuffle[i+1]]).nnz #l0 norm of sum vector plus next x2

            if d0 >= d1 and d0 >=  d2: # the next two vectors do not expand row coverage
                coverages.append(d0)

            elif d1 >= d2: # if x1 increases range more than (or equivalent) to x2, then keep x1 and make the sum z 
                z=z+XX[:,idx_shuffle[i]]
                idx_values.append(idx_shuffle[i])
                coverages.append(d1)

            else: # vice versa
                z=z+XX[:,idx_shuffle[i+1]]
                idx_values.append(idx_shuffle[i+1])
                coverages.append(d2)
            
            i+=2 # jump by 2 each time

    return len(idx_values), idx_values, coverages

In [149]:
print(idx_values)

[491, 86, 343, 359]


In [154]:
XX[:,idx_values].todense()

matrix([[0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
        [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
        

In [136]:
z.nnz

3

In [138]:
(z+XX[:,idx_shuffle[i]]).nnz

4

In [127]:
67*14 + 62

1000

In [100]:
cnt=[0,1,2,3]
cnt[2:]

[2, 3]

In [105]:
cnt=[0,1,2,3,4,5,6,7,8,9]
for x in [0,1,2,3,4,5]:
    print(x)
    if x <3:
        cnt=cnt[2:]
        print(cnt)
    else: 
        print(x)

0
[2, 3, 4, 5, 6, 7, 8, 9]
1
[4, 5, 6, 7, 8, 9]
2
[6, 7, 8, 9]
3
3
4
4
5
5


In [99]:
tst=[1,2,3]


TypeError: pop expected at most 1 argument, got 2

In [98]:
tst

[2, 3]

In [70]:
splits

[[1, 12, 10, 3, 8, 0, 2, 6, 9, 11, 4, 5, 7, 13],
 [17, 26, 22, 23, 16, 14, 21, 15, 27, 18, 25, 20, 19, 24],
 [33, 31, 41, 35, 30, 38, 32, 40, 29, 28, 36, 37, 34, 39],
 [44, 52, 55, 50, 51, 45, 47, 54, 48, 46, 53, 49, 43, 42],
 [65, 67, 58, 61, 64, 62, 57, 60, 59, 63, 69, 68, 66, 56],
 [76, 71, 72, 70, 78, 82, 73, 74, 79, 81, 75, 80, 83, 77],
 [95, 84, 89, 93, 91, 90, 94, 88, 98, 87, 96, 99, 92, 86, 85, 97]]

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.33269676, 0.        ,
         0.54187636, 0.        , 0.        , 0.        , 0.        ,
         0.30787585, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.82014348, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.38657519, 0.        , 0.        ,
         0.        , 0.        , 0